- packs/st2cd/actions/st2_web_deploy.meta.yaml
- packs/st2cd/actions/st2_web_rollback.meta.yaml
- packs/st2cd/actions/workflows/st2_web_deploy.yaml
- packs/st2cd/actions/workflows/st2_web_rollback.yaml
This adds two workflows:
* st2_web_deploy
* st2_web_rollback
and a rule:
* st2_web_master_staging
The rule looks for post commit messages on the st2web repo master branch.  On a matching event it fires the st2_web_deploy workflow to upgrade st2web to TOT on whichever host is listed as the CI host in the datastore.
Here is the help output of the deploy workflow: 
```
Deploys the latest st2web on a server
Required Parameters:
hostname
Hostname to deploy st2web on
Type: string
token
GitHub OAuth Token
Type: string
Default:
Optional Parameters:
author
Type: string
backup_dir
Location to backup old st2web to
Type: string
Default: /home/stanley/backup
branch
The branch to clone
Type: string
Default: master
repo_path
Relative GitHub repo path [USERNAME/REPO.git]
Type: string
Default: …
```
> st2web deployment workflow

- packs/mistral-dev/actions/switch.sh
- packs/mistral-dev/actions/switch.yaml
- packs/mistral-dev/pack.yaml
Initial pack to manage mistral development environments. The
mistral-dev.switch action allows developers to switch between the
stackstorm/mistral and stackforge/mistral github repositories. The
action assumes github repositories are cloned locally.
> Pack for mistral development

- packs/mistral-dev/actions/switch.sh
grep return exit code 1 if no match. This causes the action to exit with
failure.
> Fix exit code for grep

- packs/st2cd/actions/workflows/st2_packaging_st2client.yaml
Clean up and remove the ~/.pypirc file from the environment.
> Remove .pypirc file after build

- packs/st2cd/actions/st2_packaging_st2client.meta.yaml
- packs/st2cd/actions/write_pypirc.sh
- packs/st2cd/actions/write_pypirc.yaml
Remove unneeded parameters from the st2_packaging_st2client action, remove special chars from .pypirc file, and rename username/password parameters in the write_pypirc action.
> Minor fixes to workflow for uploading st2client to pypi

- packs/deploy/actions/README.md
- packs/deploy/actions/merge.py
- packs/deploy/actions/merge.yaml
- packs/deploy/actions/pack.rb
- packs/deploy/actions/pack.yaml
- packs/deploy/actions/pack_chatops.yaml
- packs/deploy/actions/parse_pack_chatops.rb
- packs/deploy/actions/parse_pack_chatops.yaml
- packs/deploy/actions/workflows/app.yaml
- packs/deploy/actions/workflows/pack_chatops.mistral.yaml
- packs/deploy/actions/workflows/pack_chatops.yaml
- packs/deploy/config.yaml
- packs/deploy/pack.yaml
- packs/deploy/rules/README.md
- packs/deploy/rules/deploy_pack_chatops.yaml
- packs/deploy/sensors/README.md
Alright, I was really hoping to wait until we finish ChatOps before I start introducing commands into our lexicon, but this one seemed too important to wait, and will also give us something to throw darts at as we go down our voyage. I also said I would do this last week, but other things ate my time. So, here's a bit of weekend hacking!
This PR introduces the ability to do rapid pack deployments on a StackStorm server via ChatOps. Very first pass, but I believe this to be the first beachhead... the speed at which we can do pack development is a bottleneck in both communication and flexibly. Unlocking this :zap: is essential to really start :racehorse:!
```
Usage: pack [options]
-i, --info INFO                  Gather info on pack deployment (version, clean)
-p, --pack PACK …
```
> Baseline pack deployment via ChatOps

- packs/st2cd/actions/create_version_tag_rule.py
- packs/st2cd/actions/create_version_tag_rule.yaml
- packs/st2cd/actions/git_branch.sh
- packs/st2cd/actions/git_branch.yaml
- packs/st2cd/actions/git_branch_remove.sh
- packs/st2cd/actions/git_branch_remove.yaml
- packs/st2cd/actions/st2_finalize_release.meta.yaml
- packs/st2cd/actions/tag_branch.sh
- packs/st2cd/actions/workflows/st2_finalize_release.yaml
- packs/st2cd/actions/workflows/st2_pytests_setup.yaml
* Create a rule to tag the release on packaging completion
* Create a workflow that performs the actual tagging and setups a new branch for the next patch release.
Testing
* Workflow tested on fork of st2.
* Rule creation itself tested but rule matching untested.
> Tag on deploy pass

- packs/st2cd/rules/st2_upgrade_staging_f20.yaml
- packs/st2cd/rules/st2_upgrade_staging_ubuntu14.yaml
I need to move these to consul but this should get us up and running for running both 0.8 and master on a staging host.
> Lookup active staging host in kvstore by branch and distro

- packs/st2cd/actions/st2_e2e_tests.meta.yaml
- packs/st2cd/actions/workflows/st2_deploy_test.yaml
- packs/st2cd/actions/workflows/st2_e2e_tests.yaml
- packs/st2cd/rules/st2_pkg_prod_master_f20.yaml
- packs/st2cd/rules/st2_pkg_prod_master_ubuntu14.yaml
- packs/st2cd/rules/st2_test_staging_f20.yaml
- packs/st2cd/rules/st2_test_staging_ubuntu14.yaml
- packs/st2cd/rules/st2cd_slack_e2e_test.yaml
This renamed the integration_tests workflow to e2e_tests, adds a step to install the tests pack, and adds the first quickstart test workflow.
> Renamed integration_tests to e2e_tests and added new quickstart test

- packs/autoscale/README.md
- packs/autoscale/actions/asg_create.yaml
- packs/autoscale/actions/workflows/asg_create.yaml
- packs/autoscale/actions/workflows/asg_deflate.yaml
- packs/autoscale/actions/workflows/asg_expand.yaml
- packs/autoscale/sensors/autoscale_governor.yaml
- packs/autoscale/sensors/autoscale_governor_sensor.py
This pull request introduces a new "status" variable which is used to prevent race conditions (multiple governor up / down events being emitted in a short time frame) in the autoscaling process.
This issue would occur if a time between the initial group creation and the first expansion / deflation event end time is greater than ``delay`` minutes or if the expansion / deflation process itself takes more than ``delay`` minutes.
> Introduce new ASG "status" variable and use it to prevent race conditions

- packs/autoscale/README.md
- packs/autoscale/actions/asg_create.yaml
- packs/autoscale/actions/workflows/asg_add_node.yaml
- packs/autoscale/actions/workflows/asg_create.yaml
- packs/autoscale/actions/workflows/asg_deflate.yaml
- packs/autoscale/actions/workflows/asg_delete_node.yaml
- packs/autoscale/actions/workflows/asg_expand.yaml
- packs/autoscale/actions/workflows/crit_alert.yaml
- packs/autoscale/rules/newrelic_crit_alert.yaml
- packs/autoscale/rules/newrelic_recovery_alert.yaml
- packs/autoscale/sensors/autoscale_governor.yaml
- packs/autoscale/sensors/autoscale_governor_sensor.py
https://gist.github.com/Kami/2d424ba856d1799809d5
Rule was referencing `trigger.long_description` field, but it looks like it should be `trigger.alert.long_description` since the top level trigger instance object doesn't have this attribute. Same issue exists for `trigger.alert_policy_name` - should be `trigger.alert.alert_policy_name`.
Here is a trigger instance in question:
```python
{'alert': {u'account_name': u'fryman.io',
u'alert_policy_name': u'Default server alert policy',
u'alert_url': u'https://rpm.newrelic.com/accounts/880740/incidents/11717078',
u'created_at': u'2015-02-03T01:07:00Z',
u'long_description': u'Alert opened: CPU > 80%',
u'message': u'CPU > 80%',
u'server_events': [{u'created_at': u'2015-02-03T01:07:00Z',
u'message': u'CPU > 60%',
u'server': u'glaswegians-clops'}, …
```
> Various autoscale fixes

- packs/st2cd/actions/workflows/st2_pkg_ubuntu14.yaml
This is related to https://github.com/StackStorm/st2/pull/1447
We were not cleaning up old packages before copying them over to the downloads server.  This was causing excessive copy times and causing errors fetching the latest version number.  The repos have been cleaned up and the bootstrap script now has the correct sort order for the versions.
> Added package clean up

- packs/hubot/actions/post_result.py
- packs/hubot/actions/post_result.yaml
- packs/hubot/config.yaml
- packs/hubot/rules/notify_hubot.yaml
* The post_result action is used to post notification results to hubot. This new action
manages result parsing closer to st2 to hide complexity from hubot.
* The channel rule is modified to use this new action.
Requires https://github.com/StackStorm/st2/pull/1475
> Add post_result action

- packs/st2cd/actions/workflows/st2_pkg_ubuntu14.yaml
STORM-1360 outlined an issue with package cross contamination in the repos.  This adds a little more package pruning from the build servers and tightens up the rsync.
> Fixing package cross contamination issue STORM-1360

- packs/hubot/actions/post_result.py
As reported by @jtopjian, this PR fixes conditions where raw JSON is passed
to hubot.post_result and the `strip()` call was failing. This is because
`stdout` is converted to JSON by the localrunner and pythonrunner before
being returned.
Fixes #218
> Allow raw JSON to be passed to hubot.post_result

- packs/st2cd/actions/st2cd_add_annotation_for_release.yaml
- packs/st2cd/actions/workflows/st2_add_annotation_for_release.yaml
- packs/st2cd/rules/st2_add_librato_annotation_for_release.yaml
With this change we will create a new annotation in Librato when a release is created.
This way we can correlate other metrics to those annotations.
Depends on #169
> [RFC] Create a Librato annotation when a release is created

- packs/st2cd/actions/puprun.yaml
This PR adds the ability to run arbitrary puppet environments, which map 1:1 to branches on the st2puppet project.
> Add Branch Deployments to Puprun Action

- packs/st2cd/actions/kvstore.py
This PR attempts to load up the old and new libraries to access the K/V store, allowing compatibility with older running nodes (<0.8 ) and newer nodes (>=0.9)
/cc @DoriftoShoes
> st2cd KVStore Compatibility >=0.9

- packs/st2cd/actions/workflows/st2_e2e_tests.yaml
Re-enabling selenium tests; if they fail, however, the overall flow will still succeed. This will allow me to debug random failures which were observed during CI execution (not reproducible elsewhere)
> Re-enabling selenium tests

- packs/st2cd/actions/st2_e2e_tests.meta.yaml
None is requires, thus should not alter default behavior
> Added windows* parameters

- packs/st2cd/actions/workflows/st2_e2e_tests.yaml
Since those are new tests, in order to make sure the build is not failing if there are any issues with them, failure of those tests will be ignored.
> Added test_windows_runners and test_timer_rule

- packs/st2cd/actions/create_vm_role.meta.yaml
- packs/st2cd/actions/set_hostname_cloud.yaml
- packs/st2cd/actions/st2_finalize_release.meta.yaml
- packs/st2cd/actions/st2_tag_release_meta.yaml
- packs/st2cd/rules/st2_deploy_test_v0.11_f20.json
- packs/st2cd/rules/st2_deploy_test_v0.11_ubuntu14.json
- packs/st2cd/rules/st2_deploy_test_v0.12_f20.json
- packs/st2cd/rules/st2_deploy_test_v0.12_ubuntu14.json
- packs/st2cd/rules/st2web_deploy_staging_f20.yaml
- packs/st2cd/rules/st2web_deploy_staging_ubuntu14.yaml
These are issues discovered during the 0.12 release and updated locally.  I also lumped in some changes needed for RHEL7 support in here.
* Add RHEL7 to distro enum in create_vm_role workflow and associated actions
* Switch to git protocol from https for release workflows that need to write to git repos
* Use kvstore for unstable host version in st2web deploy workflows for master - previously hardcoded.
* Added st2_deploy test for versions 0.11 and 0.12 - These were written locally on the build server
> Update from 012 release

- packs/st2ci_mistral/actions/install_mistral.sh
Mistral is still using YAQL 0.2.7 and it has conflicts with other dependencies. The hack here is temporary to get thru the installation of Mistral. There'll be no negative impact from this fix.
> Temporary fix YAQL dependency for Mistral install

- packs/typeform/config.yaml
- packs/typeform/sensors/registration_sensor.py
The Typeform sensor was dying on timeout to the Typeform API.  This adds a configurable timeout and number of retries.
> Add timeout and retries to sensor

- packs/st2-demos/actions/diskspace_remediation.meta.yaml
- packs/st2-demos/actions/workflows/diskspace_remediation.yaml
- packs/st2-demos/rules/diskspace_remediation.yaml
This PR adds a Sensu silence action to the diskspace autoremediation workflow.  In order to silence the check a new parameter had to be added: check_name.  The accompanying rule was also updated to pass the check name it receives in the trigger in to the workflow.
> Added check name parameter and silence sensu action

- packs/autoscale/pack.yaml
```
Traceback (most recent call last):
File "/mnt/st2/st2common/st2common/bootstrap/base.py", line 100, in register_pack
pack_db = self._register_pack(pack_name=pack_name, pack_dir=pack_dir)
File "/mnt/st2/st2common/st2common/bootstrap/base.py", line 137, in _register_pack
pack_db = Pack.add_or_update(pack_db)
File "/mnt/st2/st2common/st2common/persistence/base.py", line 155, in add_or_update
model_object = cls._get_impl().add_or_update(model_object)
File "/mnt/st2/st2common/st2common/models/db/__init__.py", line 152, in add_or_update
instance.save()
File "/mnt/st2/virtualenv/local/lib/python2.7/site-packages/mongoengine/document.py", line 224, in save
self.validate(clean=clean)
File "/mnt/st2/virtualenv/local/lib/python2.7/site-packages/mongoengine/base/document.py", line 323, in …
```
> Fix invalid email in autoscale pack

- packs/st2-demos/actions/check_dir_size.py
While checking out the [Auto-remediation by example: handling out-of-disk-space](https://stackstorm.com/2015/10/05/auto-remediation-out-of-disk-space/) blog post.  I came a cross a couple of very minor bugs that prevented the script from running on the command line.
> Fixes for check_dir_size.py - Make --threshold required and correct a typo (use instead of usage)

- packs/st2ci/rules/mistral_os_master.yaml
Temporary prevent mistralclient changes from upstream to merge into our fork.
> Temporary disable mistral merge with upstream rule

- packs/typeform/README.md
- packs/typeform/actions/chains/register_and_invite.yaml
- packs/typeform/actions/chains/send_slack_invite.yaml
The following was done for the TypeForm pack:
The send_slack_invite.yaml file was in the rules folder and not
actions/chains.  Moved this to the correct folder.
The register_and_invite.yaml chain has a ref: “mysql.insert” although
that pack doesn’t exist.  I’ve updated this to point to
st2-mysql.insert which does exist.
The typeform sensor requires specific fields specified in the
registration_sensor.py file but there were no directions for this.
Added directions specifying that it’s needed as well as how to find the field IDs you need.
> TypeForm Pack updates

- packs/st2ci/actions/git_merge_upstream.sh
The sha post merge upstream in the fork is not necessary the same sha as upstream.
> Remove the sha check

- packs/mistral-dev/actions/install.sh
The command "python setup.py develop" for installing mistral required a later version of setuptools.
> Upgrade setuptools

- packs/mistral-dev/actions/workflows/setup.mistral.yaml
The task result is not referenced using the task function in mistral workflows.
> Fix references to task result in mistral workflows

- packs/st2-demos/actions/bgp_down_remed_chain.meta.yaml
- packs/st2-demos/actions/bgp_down_remed_workflow.yaml
- packs/st2-demos/actions/chains/bgp_down_remed_chain.yaml
- packs/st2-demos/actions/chains/link_flap_remed_chain.yaml
- packs/st2-demos/actions/link_flap_remed_chain.meta.yaml
- packs/st2-demos/actions/link_flap_remed_workflow.yaml
- packs/st2-demos/actions/workflows/bgp_down_remed_workflow.yaml
- packs/st2-demos/actions/workflows/link_flap_remed_workflow.yaml
- packs/st2-demos/rules/splunk_bgp_down.yaml
- packs/st2-demos/rules/splunk_link_flap.yaml
This PR is for adding **ST2-Splunk-VDX** integration demo workflows to the *st2-demos* pack. 
Workflows are created for 2 use cases:
1. Auto-remediation for 'link down' event:
Splunk detects link flap event from vdx syslog and does a webhook call to ST2 which then triggers a workflow. Both mistral and action chain based workflows are defined and either can be used as the action for the webhook trigger. Both workflows do the following: 
- Notifies of event on slack channel
- Pulls interface config from the switch and posts to slack 
- Tries to bring the interface back up (using clicrud config command action)
- Pulls interface details from the switch and posts to slack 
- Creates a JIRA ticket for the event
1. Auto-remediation for 'BGP peer down' event:
Splunk detects BGP peer down event …
> Adding ST2-Splunk-VDX integration workflows
